stages:
  - trigger
  - deploy

# 触发后端 pipeline
backend:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/backend.yml
    strategy: depend
  rules:
    - changes:
        - backend/**/*

# 触发前端 pipeline
frontend:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/frontend.yml
    strategy: depend
  rules:
    - changes:
        - frontend/**/*

deploy:
  stage: deploy
  trigger:
    include:
      - local: .gitlab/deploy.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - backend/**/*
        - frontend/**/*
        - deploy/prod/**/*
        - .gitlab-ci.yml
        - .gitlab/**/*
