services:
  mysql:
    image: mysql:8.0
    container_name: campushub-mysql-prod
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai

    volumes:
      - mysql-data-prod:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} --silent" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - campushub-net-prod

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: campushub-frontend-prod
    restart: unless-stopped

    networks:
      - campushub-net-prod

  backend:
    image: ${BACKEND_IMAGE}
    container_name: campushub-backend-prod
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FILE_STORAGE_ROOT: ${FILE_STORAGE_ROOT}
      TZ: Asia/Shanghai

    volumes:
      - backend-file-root-prod:${FILE_STORAGE_ROOT}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - campushub-net-prod

  nginx:
    image: nginx:1.27-alpine
    container_name: campushub-nginx-prod
    restart: unless-stopped

    environment:
      TZ: Asia/Shanghai

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started

    networks:
      - campushub-net-prod

  certbot:
    image: certbot/certbot
    container_name: certbot
    environment:
      TZ: Asia/Shanghai
    profiles:
      - cert
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt


volumes:
  mysql-data-prod:
  backend-file-root-prod:

networks:
  campushub-net-prod:
    driver: bridge