stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:3.20

  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - cp "$SERVER_SSH_KEY" ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

  script:
    - ssh "$SERVER_USER@$SERVER_HOST" "
        cd $SERVER_PROJECT_DIR &&
        docker compose -f docker-compose.yml pull &&
        docker compose -f docker-compose.yml up -d &&
        docker image prune -f
      "